[tools]
"aqua:itchyny/mmv" = "latest"
"aqua:k1LoW/tbls" = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bun = "latest"
deno = "2.5.6"
doggo = "latest"
ghq = "latest"
github-cli = "latest"
"github:skanehira/ghost" = "latest"
go = "latest"
"go:github.com/mattn/sleepy" = "latest"
gojq = "latest"
gron = "latest"
hurl = "latest"
jq = "latest"
lazygit = "latest"
"npm:@github/copilot" = "latest"
php = "latest"
qdns = "latest"
ripgrep = "latest"
rust = "latest"
tbls = "latest"
"ubi:superultrainc/sup" = "latest"

[env]
COMPOSER_HOME = "~/.config/composer"
